"""Adiciona campo instituicao na tabela ativos

Revision ID: 5b19b8709657
Revises: 8beaae2d8826
Create Date: 2025-12-24 00:27:53.802606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b19b8709657'
down_revision = '8beaae2d8826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ativos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instituicao', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ativos', schema=None) as batch_op:
        batch_op.drop_column('instituicao')

    # ### end Alembic commands ###
