"""Adiciona tabelas de investimentos (TipoAtivo, Ativo, TransacaoAtivo, Dividendo)

Revision ID: 8beaae2d8826
Revises: 0b1f60efa610
Create Date: 2025-12-24 00:04:31.315334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8beaae2d8826'
down_revision = '0b1f60efa610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_ativos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('ativos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tipo_ativo_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('preco_medio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ultimo_preco', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ultima_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('variacao_dia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tipo_ativo_id'], ['tipos_ativos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dividendos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor_por_acao', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('quantidade_acoes', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_com', sa.Date(), nullable=True),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('recebido', sa.Boolean(), nullable=True),
    sa.Column('observacao', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacoes_ativos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('taxa_corretagem', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('outros_custos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('data_operacao', sa.Date(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacoes_ativos')
    op.drop_table('dividendos')
    op.drop_table('ativos')
    op.drop_table('tipos_ativos')
    # ### end Alembic commands ###
